# Generated by Django 2.1 on 2018-08-23 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='Text',
        ),
    ]
